theme: jekyll-theme-cayman
title: Has AlTaiar
description: Rambling of an old man on software, life, and stuff
social-links:
  twitter: http://twitter.com
  linkedin: http://linkedin.com
  contact: http://forms.google.com
