theme: jekyll-theme-cayman
title: Has AlTaiar
description: Rambling of an old man on software, life, and stuff
social-links:
  twitter: https://twitter.com/hasaltaiar
  linkedin: https://www.linkedin.com/in/altaiar