
title: Has Altaiar
description: Occasionally wise, frequently random thoughts on technology, life, and everything in between
google_analytics: UA-121904616-1
# url: "https://www.hasaltaiar.com.au" 
plugins:
social-links:
  twitter: https://twitter.com/hasaltaiar
  linkedin: https://www.linkedin.com/in/altaiar
