# GitHub Actions Workflow for Preview Deployment
# This workflow deploys the static site to the 'gh-pages-preview' branch for review before going live.

name: Deploy Preview to GitHub Pages

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to gh-pages-preview branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages-preview
          force_orphan: true
